//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace firmware_wintools.Lang.Tools {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MkEdimaxImgRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MkEdimaxImgRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("firmware_wintools.Lang.Tools.mkedimaximg.MkEdimaxImgRes", typeof(MkEdimaxImgRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   model must be 4 characters long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidModelLen {
            get {
                return ResourceManager.GetString("Error.InvalidModelLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   signature must be 4 characters long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidSignatureLen {
            get {
                return ResourceManager.GetString("Error.InvalidSignatureLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   input file is too large に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LargeInFile {
            get {
                return ResourceManager.GetString("Error.LargeInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no or invalid flash address specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoInvalidFlash {
            get {
                return ResourceManager.GetString("Error.NoInvalidFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no or invalid start address specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoInvalidStart {
            get {
                return ResourceManager.GetString("Error.NoInvalidStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no model specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoModel {
            get {
                return ResourceManager.GetString("Error.NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no signature specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoSignature {
            get {
                return ResourceManager.GetString("Error.NoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   add Edimax header and checksum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncDesc {
            get {
                return ResourceManager.GetString("FuncDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -b			use &quot;big endian&quot; mode
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_b {
            get {
                return ResourceManager.GetString("Help.Options.b", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -f &lt;flash&gt;		use the &lt;flash&gt; address for image header
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_f {
            get {
                return ResourceManager.GetString("Help.Options.f", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -m &lt;model&gt;		use &lt;model&gt; for image header
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_m {
            get {
                return ResourceManager.GetString("Help.Options.m", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -s &lt;signature&gt;	use &lt;signature&gt; for image header
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_s {
            get {
                return ResourceManager.GetString("Help.Options.s", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -S &lt;start&gt;		use the &lt;start&gt; address for image header
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_s2 {
            get {
                return ResourceManager.GetString("Help.Options.s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage: firmware-wintools mkedimaximg [OPTIONS...]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===== mkedimaximg mode ===== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///    BE mode	: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_BE {
            get {
                return ResourceManager.GetString("Info.BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    flash addr	: 0x{0:X} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_FlashAddr {
            get {
                return ResourceManager.GetString("Info.FlashAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    model		: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Model {
            get {
                return ResourceManager.GetString("Info.Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///    signature	: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Signature {
            get {
                return ResourceManager.GetString("Info.Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///    start addr	: 0x{0:X} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_StartAddr {
            get {
                return ResourceManager.GetString("Info.StartAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///       {0}		: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_FuncDesc_Fmt {
            get {
                return ResourceManager.GetString("Main.FuncDesc.Fmt", resourceCulture);
            }
        }
    }
}
