//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace firmware_wintools.Lang.Tools {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuffaloEncRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuffaloEncRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("firmware_wintools.Lang.Tools.buffalo_enc.BuffaloEncRes", typeof(BuffaloEncRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   specified file is too big (&gt;= 2GiB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BigFile {
            get {
                return ResourceManager.GetString("Error.BigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   checksum doesn&apos;t match, exiting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CksumNotMatch {
            get {
                return ResourceManager.GetString("Error.CksumNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailDecrypt {
            get {
                return ResourceManager.GetString("Error.FailDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to decrypt header or data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailDecryptData {
            get {
                return ResourceManager.GetString("Error.FailDecryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailEncrypt {
            get {
                return ResourceManager.GetString("Error.FailEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to encrypt data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailEncryptData {
            get {
                return ResourceManager.GetString("Error.FailEncryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to encrypt header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailEncryptHeader {
            get {
                return ResourceManager.GetString("Error.FailEncryptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to load data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailLoadData {
            get {
                return ResourceManager.GetString("Error.FailLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to load footer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailLoadFooter {
            get {
                return ResourceManager.GetString("Error.FailLoadFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed to load header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_FailLoadHeader {
            get {
                return ResourceManager.GetString("Error.FailLoadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   length of magic must be {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_InvalidMagicLen {
            get {
                return ResourceManager.GetString("Error.InvalidMagicLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   specified offset &quot;{0}&quot; is larger than the size of input file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LargeOffset {
            get {
                return ResourceManager.GetString("Error.LargeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   specified key &quot;{0}&quot; is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LongKey {
            get {
                return ResourceManager.GetString("Error.LongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   specified product name &quot;{0}&quot; is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LongProduct {
            get {
                return ResourceManager.GetString("Error.LongProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   specified version &quot;{0}&quot; is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_LongVersion {
            get {
                return ResourceManager.GetString("Error.LongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no key is specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoKey {
            get {
                return ResourceManager.GetString("Error.NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no product specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoProduct {
            get {
                return ResourceManager.GetString("Error.NoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no version specified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NoVersion {
            get {
                return ResourceManager.GetString("Error.NoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   encrypt/decrypt firmware for Buffalo devices に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FuncDesc {
            get {
                return ResourceManager.GetString("FuncDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -d			use decrypt mode instead of encrypt
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_d {
            get {
                return ResourceManager.GetString("Help.Options.d", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -F			force decryption if checksum is error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_F {
            get {
                return ResourceManager.GetString("Help.Options.F", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -k &lt;key&gt;		use &lt;key&gt; for encryption (default: &quot;{0}&quot;)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_k {
            get {
                return ResourceManager.GetString("Help.Options.k", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -l			use longstate encryption/decryption method
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_l {
            get {
                return ResourceManager.GetString("Help.Options.l", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -m &lt;magic&gt;		use &lt;magic&gt; for encryption (default: &quot;{1}&quot;)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_m {
            get {
                return ResourceManager.GetString("Help.Options.m", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -O &lt;offset&gt;		offset of encrypted data in file (for decryption)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_o2 {
            get {
                return ResourceManager.GetString("Help.Options.o2", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -p &lt;product&gt;		use &lt;product&gt; name for encryption
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_p {
            get {
                return ResourceManager.GetString("Help.Options.p", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -S &lt;size&gt;		size of unencrypted data in file (for encryption)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string help_Options_S {
            get {
                return ResourceManager.GetString("help.Options.S", resourceCulture);
            }
        }
        
        /// <summary>
        ///     -v &lt;version&gt;		use &lt;version&gt; for encryption
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Options_v {
            get {
                return ResourceManager.GetString("Help.Options.v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage: {0}buffalo-enc [OPTIONS...]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===== buffalo-enc mode ({0}) ===== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Checksum	: 0x{0:x} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Cksum {
            get {
                return ResourceManager.GetString("Info.Cksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Data len	: {0} bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DataLen {
            get {
                return ResourceManager.GetString("Info.DataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Decrypt {
            get {
                return ResourceManager.GetString("Info.Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Encrypt {
            get {
                return ResourceManager.GetString("Info.Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    key		: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Key {
            get {
                return ResourceManager.GetString("Info.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///    longstate	: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Longstate {
            get {
                return ResourceManager.GetString("Info.Longstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Magic		: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Magic {
            get {
                return ResourceManager.GetString("Info.Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Product	: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Product {
            get {
                return ResourceManager.GetString("Info.Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Seed		: 0x{0:X02} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Seed {
            get {
                return ResourceManager.GetString("Info.Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Version	: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Version {
            get {
                return ResourceManager.GetString("Info.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///       {0}		: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Main_FuncDesc_Fmt {
            get {
                return ResourceManager.GetString("Main.FuncDesc.Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   checksum doesn&apos;t match, ignoring... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warn_CksumNotMatch {
            get {
                return ResourceManager.GetString("Warn.CksumNotMatch", resourceCulture);
            }
        }
    }
}
